issue #3 and clean up

diff --git a/borg-wrapper b/borg-wrapper
--- a/borg-wrapper
+++ b/borg-wrapper
@@ -5,93 +5,112 @@ set -o errexit
 DEBUG=false
 BORG_PARAMS=
 
-function usage {
-  echo "This is a very simple wrapper to borg."
-  echo "borg-wrapper CONFIG-NAME COMMAND [BORG-PARAMS] [OPTION]"
-  echo "CONIG_NAME: The name of the repository configuration."
-  echo "OPTION:"
-  echo "  -d       Print some debug info."
-  echo "COMMAND:"
-  echo "  backup   Start the backup of the named configuration, e.g."
-  echo "           - borg-wrapper vmail backup"
-  echo "  check    Verifies the consistency of a repository and the "
-  echo "           corresponding archives of a named configuration, e.g."
-  echo "           - borg-wrapper vmail check"
-  echo "  info     Print infos of a repo or a backup, if specified."
-  echo "           Archive filters can be use, e.g. "
-  echo "           - borg-wrapper vmail info \"--last 1\""
-  echo "           - borg-wrapper vmail info \"vmail-2021-10-31_16:40\""
-  echo "  list     List all backups of a repo."
-  echo "  mount    Mount a borg backup, which can be selected from a list."
-  echo "  umount   Unmount a borg mount point."
-  exit 0
+usage() {
+   echo "This is a very simple wrapper to borg."
+   echo "borg-wrapper CONFIG-NAME COMMAND [BORG-PARAMS] [OPTION]"
+   echo "CONIG_NAME: The name of the repository configuration."
+   echo "OPTION:"
+   echo "  -d       Print some debug info."
+   echo "COMMAND:"
+   echo "  backup   Start the backup of the named configuration, e.g."
+   echo "           - borg-wrapper vmail backup"
+   echo "  check    Verifies the consistency of a repository and the "
+   echo "           corresponding archives of a named configuration, e.g."
+   echo "           - borg-wrapper vmail check"
+   echo "  info     Print infos of a repo or a backup, if specified."
+   echo "           Archive filters can be use, e.g. "
+   echo "           - borg-wrapper vmail info \"--last 1\""
+   echo "           - borg-wrapper vmail info \"vmail-2021-10-31_16:40\""
+   echo "  list     List all backups of a repo."
+   echo "  mount    Mount a borg backup, which can be selected from a list."
+   echo "  umount   Unmount a borg mount point."
+   exit 0
 }
 
-function backup {
+backup() {
    # trigger the backup
-   [[ -z $BACKUP_CMD ]] && echo "Missing config BACKUP_CMD!" && exit 10;
-   _begin_date=$(date +%s)
+   [[ -z $BACKUP_CMD ]] && echo "Missing config BACKUP_CMD!" && exit 10
+   local _begin_date=$(date +%s)
    eval "${BACKUP_CMD}"
-   
-   if [ "$DIR_MONITORING" != "n/a" ] ; then
-     # write data for monitoring
-     _end_date=$(date +%s)
-     _duration=$(expr $_end_date - $_begin_date)
-     _now=$(date '+%F %T')
-     echo "${_now},${_duration}" > "${DIR_MONITORING}/${CONFIG}"
+
+   if [ "$DIR_MONITORING" != "n/a" ]; then
+      # write data for monitoring
+      _end_date=$(date +%s)
+      _duration=$(expr $_end_date - $_begin_date)
+      _now=$(date '+%F %T')
+      echo "${_now},${_duration}" >"${DIR_MONITORING}/${CONFIG}"
    fi
 }
 
-function list {
-    borg list
+list() {
+   borg list
 }
 
-function check {
-	borg check
+check() {
+   borg check
 }
 
-function info {
-    _temp=""
-    if [[ ! -z $BORG_PARAMS ]] ; then
-       if [[ $BORG_PARAMS == -* ]] ; then
-          _temp="${BORG_PARAMS}" 
-       else
-          # get repo info
-          _temp="${BORG_REPO}::${BORG_PARAMS}"
-       fi
+info() {
+   local _temp=""
+   if [[ ! -z $BORG_PARAMS ]]; then
+      if [[ $BORG_PARAMS == -* ]]; then
+         _temp="${BORG_PARAMS}"
+      else
+         # get repo info
+         _temp="${BORG_REPO}::${BORG_PARAMS}"
+      fi
    fi
    borg info ${_temp}
 }
 
-function mount {
-    mountpoint -q $DIR_MOUNT && echo "${DIR_MOUNT} already mounted!" && exit 10
-    _items=()
-    _idx=1
-    # fetch the backup items of a repo
-    for _item in $(borg list --short | awk '{printf "%s\n", $1}') ; do
-        _items[_idx]="$_item"
-       ((_idx++))
-    done
-	# list the backup items of a repo
-	for _key in "${!_items[@]}"; do
-        printf "%2d) %s\n" "$_key" "${_items[$_key]}"
-	done
-	read -p "Select a backup: " _input
-	[ ! -v '_items[$_input]' ] && echo "Wrong selection!" && exit 10
-	_selected=${_items[$_input]}
-	echo "Selected: ${_selected}"
-	borg mount $BORG_REPO::${_selected} ${DIR_MOUNT}
-	if [ $? -eq 0 ]; then
-	   echo "${_selected} successful mounted at ${DIR_MOUNT}"
-	else
-	   echo "Mount failed!"
-	fi
+is_mountpoint() {
+   local dir="$DIR_MOUNT"
+   dir="${dir%/}"
+
+   if [ ! -d "$dir" ]; then
+      echo "$dir is not a directory"
+      return 1
+   fi
+
+   if command -v findmnt >/dev/null 2>&1; then
+      findmnt -rn -o TARGET | grep -qx "$dir"
+      return $?
+   fi
+
+   # methode for MacOS or if findmnt not available
+   mount | grep -E "( on $dir | $dir on )" >/dev/null 2>&1
+   return $?
 }
 
-function umount {
-    ! mountpoint -q $DIR_MOUNT && echo "${DIR_MOUNT} isn't mounted!" && exit 10
-    borg umount ${DIR_MOUNT}
-    echo "Successful umounted: ${DIR_MOUNT}"
+mount() {
+   is_mountpoint && echo "${DIR_MOUNT} already mounted!" && exit 10
+   _items=()
+   _idx=1
+   # fetch the backup items of a repo
+   for _item in $(borg list --short | awk '{printf "%s\n", $1}'); do
+      _items[_idx]="$_item"
+      ((_idx++))
+   done
+   # list the backup items of a repo
+   for _key in "${!_items[@]}"; do
+      printf "%2d) %s\n" "$_key" "${_items[$_key]}"
+   done
+   read -p "Select a backup: " _input
+   [ ! -v '_items[$_input]' ] && echo "Wrong selection!" && exit 10
+   _selected=${_items[$_input]}
+   echo "Selected: ${_selected}"
+   borg mount $BORG_REPO::${_selected} ${DIR_MOUNT}
+   if [ $? -eq 0 ]; then
+      echo "${_selected} successful mounted at ${DIR_MOUNT}"
+   else
+      echo "Mount failed!"
+   fi
+}
+
+umount() {
+   ! is_mountpoint $DIR_MOUNT && echo "${DIR_MOUNT} isn't mounted!" && exit 10
+   borg umount ${DIR_MOUNT}
+   echo "Successful umounted: ${DIR_MOUNT}"
 }
 
 [[ $# -lt 1 ]] && usage && exit 0
@@ -106,18 +125,18 @@ unset BACKUP
 
 ## parsing the arguments
 _cnt=1
-for ((i = 1; i <= $#; i++ )); do
-  arg=${!i}
-  #printf '(%i) %s\n' $_cnt "Arg $i: ${arg}"
-  [[ $arg == "-d" ]] && DEBUG=true && continue;
-  [[ $arg == "umount" ]] && CMD="${arg}" && continue;
-  [ $_cnt -eq 1 ] && CONFIG="${arg}" && ((_cnt++)) && continue;
-  [ $_cnt -eq 2 ] && CMD="${arg}" && ((_cnt++)) && continue;
-  [ $_cnt -eq 3 ] && BORG_PARAMS="${arg}" && ((_cnt++)) && continue;
+for ((i = 1; i <= $#; i++)); do
+   arg=${!i}
+   #printf '(%i) %s\n' $_cnt "Arg $i: ${arg}"
+   [[ $arg == "-d" ]] && DEBUG=true && continue
+   [[ $arg == "umount" ]] && CMD="${arg}" && continue
+   [ $_cnt -eq 1 ] && CONFIG="${arg}" && ((_cnt++)) && continue
+   [ $_cnt -eq 2 ] && CMD="${arg}" && ((_cnt++)) && continue
+   [ $_cnt -eq 3 ] && BORG_PARAMS="${arg}" && ((_cnt++)) && continue
 done
 
 if [ "$DIR_MONITORING" = "" ]; then
-   DIR_MONITORING="n/a";
+   DIR_MONITORING="n/a"
 fi
 if [ "$DEBUG" = true ]; then
    echo "base-wrapper parameters:"
@@ -129,7 +148,7 @@ fi
 
 ## check settings & read the config
 repo_conf "${CONFIG}"
-[ "$DIR_MONITORING" != "n/a"  ] && [ ! -d "$DIR_MONITORING" ] && mkdir -p "$DIR_MONITORING" && echo "Created missing directory: $DIR_MONITORING"
+[ "$DIR_MONITORING" != "n/a" ] && [ ! -d "$DIR_MONITORING" ] && mkdir -p "$DIR_MONITORING" && echo "Created missing directory: $DIR_MONITORING"
 
 if [[ $DEBUG = true ]]; then
    echo "repo parameters:"
@@ -142,13 +161,13 @@ fi
 
 ## process
 case $CMD in
-   list) list;;
-   info) info;;
-   check) check;;
-   backup) backup;;
-   mount) mount;;
-   umount) umount;;
-   *) echo "Unknown borg-wrapper command: ${CMD}" && exit 10;;
+list) list ;;
+info) info ;;
+check) check ;;
+backup) backup ;;
+mount) mount ;;
+umount) umount ;;
+*) echo "Unknown borg-wrapper command: ${CMD}" && exit 10 ;;
 esac
 
 logger -t borg-wrapper "successful processed [$CONFIG] -> $CMD"
